# We use Travis CI only to run check-webkit-style
language: python
python: "2.7"
sudo: false
git:
  depth: 3
  sparse_checkout: .travis-sparse-checkout
script: Tools/Scripts/check-webkit-style -g origin/qtwebkit-stable..
install: true
